### ISSUE TITLE
Species link from tree pop-up is malformed

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ConektLegumes#10]
Reproduce thus:
https://conekt.legumeinfo.org/tree/view/6975 
Click on phavu.G19833.gnm1.ann1.Phvul.010G077300, 2nd gene from top to show the popup window titled Node.
Hover over the Taxonomy: Phaseolus vulgaris (phavu) to see the link =  'http://conekt/species/view/1'. This is a non-productive link. It should be https://conekt.legumeinfo.org/species/view/1

**Wellformed in dev-conekt**
In the dev-conekt it is wellformed: http://localhost:5000/species/view/1

**Comment by sdash-github** [comment]
Is it related to reverse-proxy??? 
I don't have a clue what is happening here.

**Comment by adf-ncgr** [comment]
It seems like it is almost certainly related to reverse-proxy but I'm not sure why the other change I made wouldn't have fixed it. I'll try to look at it some more.

**Comment by adf-ncgr** [comment]
well, I'm now not sure if I'm more puzzled as to why it is not working for the production version or as to why it is working on the development version. The links are embedded in XML that gets returned via an AJAX call. I think this means that something in the proxying has to be rewriting them, but we're not doing proxy-html type url rewriting that I know of (although it is enabled on fisher for other reasons). It does not appear to be due to either the apache hosting (because the apache hosted version of fisher works correctly) or due to the https layer on hardy (because if I disable the RewriteEngine and allow plain http: requests the content is still wrongly formed). I went ahead and enabled mod_proxy_html on hardy just to see if there might be some difference due to that but it didn't seem to alter the behavior (I wouldn't really have expected it to without some further configuration changes). I will leave that module in place as it may provide a way of handling the problem but it's very strange to me what could be causing the difference in behavior of the two different hosting set-ups. The code internally seems to be using the same flask method "url_for" in order to generate the URLs that is used elsewhere, so it seems like something must happen in the proxying layer.

stumped for now, so just documenting what I've looked at in hopes I won't go down the same dead ends again when I pick it back up in the new year...

**Comment by adf-ncgr** [comment]
I've found a provisional fix for this that seems to be working (more or less ) for now; it's based on info here: 
https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/#deploying-proxy-setups
but still puzzled as to why the proxying works on the dev-server without needing this.

I'm going to leave this issue open for now in case something less mysterious occurs to explain the situation (also the current fix isn't constructing the URLs with https although this doesn't cause any issue in terms of the web app functionality)

**Comment by adf-ncgr** [comment]
OK after consulting @sammyjava his eagle eye saw the subtle difference in the proxy configs between dev and prod versions that was causing this issue (absence of ProxyPreserveHost directive); I've fixed the config and disabled my earlier provisional fix and am happily closing this.
